apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nayris
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    path: manifests/argocd/apps/nayris
    repoURL: https://github.com/Kounex/cluster-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true