apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-application-manager
  namespace: kounex-argocd
spec:
  destination:
    namespace: kounex-argocd
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    path: environments/jonas-ocp
    repoURL: https://github.com/Kounex/cluster-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true