apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-manager
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    path: environments/jonas-ocp
    repoURL: https://github.com/Kounex/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true