apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../environments/bootstrap
  - ../../environments/jonas-ocp

resources:
  - namespace-kounex-argocd.yaml
  - application-cluster-application-manager.yaml