apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../environments/bootstrap
  - ../../environments/jonas-ocp

resources:
  - argocd-namespace.yaml
  - cluster-config-manager.yaml