apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-operator-system

bases:
  - ../../../environments/bootstrap

resources:
  - argocd-namespace.yaml
  - cluster-config-manager.yaml