apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kounex-argocd

bases:
  - ../../environments/bootstrap
  - ../../environments/jonas-ocp

resources:
  - namespace-kounex-argocd.yaml