apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../environments/bootstrap
  - ../../environments/jonas-ocp

resources:
  - application-cluster-config-manager.yaml